version: '3.4'

services:
  catalog.db:
    image: mongo

  catalog.application.api:
    image: ${DOCKER_REGISTRY-}catalogapplicationapi
    build:
      context: .
      dockerfile: Services/Catalog/Application/Catalog.Application.API/Dockerfile

volumes:
  mongo.data: